import { airtableService } from '../services/airtableService'

/**
 * Debug utility to help identify Airtable schema issues
 * Call from browser console: window.airtableDebug.testSchema()
 */

export const testAirtableSchema = async () => {
  console.log('🔍 Testing Airtable schema...')
  
  // Test with minimal data first - using separate date and time
  const testEvent = {
    title: 'Test Event Schema',
    description: 'Testing the Airtable schema with separate date and time fields',
    date: '2024-12-01',
    time: '10:00',
    location: 'Test Location',
    capacity: 10,
    organizerId: 'test-organizer-123'
  }
  
  try {
    console.log('📤 Attempting to create test event with date string format...')
    const result = await airtableService.createEvent(testEvent)
    console.log('✅ Success! Event created:', result)
    return result
  } catch (error) {
    console.log('❌ Failed with date string format:', error)
    
    // If that fails, let's try to inspect what fields are expected
    if (error instanceof Error && error.message.includes('Unknown field name')) {
      const fieldMatch = error.message.match(/Unknown field name: "([^"]+)"/)
      if (fieldMatch) {
        console.log(`🔍 Unknown field: ${fieldMatch[1]}`)
        console.log('💡 This suggests the Airtable schema doesn\'t have this field')
      }
    }
    
    if (error instanceof Error && error.message.includes('cannot accept the provided value')) {
      console.log('💡 This suggests the field exists but the value format is wrong')
      console.log('🔄 The service will now try ISO datetime format automatically')
    }
    
    return error
  }
}

export const listAirtableEvents = async () => {
  console.log('📋 Attempting to list existing events to understand schema...')
  
  try {
    // Try to get events by a test organizer
    const events = await airtableService.getEventsByOrganizer('test-organizer')
    console.log('✅ Events retrieved:', events)
    
    if (events.length > 0) {
      console.log('📊 Sample event structure:', events[0])
    } else {
      console.log('📭 No events found for test organizer')
    }
    
    return events
  } catch (error) {
    console.log('❌ Failed to retrieve events:', error)
    return error
  }
}

export const debugAirtableConnection = async () => {
  console.log('🔗 Testing Airtable connection...')
  
  try {
    // Try a simple GET request to see if connection works
    const response = await fetch(`https://api.airtable.com/v0/${import.meta.env.VITE_AIRTABLE_BASE_ID}/Events?maxRecords=1`, {
      headers: {
        'Authorization': `Bearer ${import.meta.env.VITE_AIRTABLE_API_KEY}`,
        'Content-Type': 'application/json'
      }
    })
    
    if (response.ok) {
      const data = await response.json()
      console.log('✅ Connection successful!')
      console.log('📊 Sample response:', data)
      
      if (data.records && data.records.length > 0) {
        console.log('🏗️ Actual field structure:', Object.keys(data.records[0].fields))
        console.log('📋 Field details:', data.records[0].fields)
      } else {
        console.log('📭 No existing records found')
      }
      
      return data
    } else {
      console.log('❌ Connection failed:', response.status, response.statusText)
      const errorData = await response.text()
      console.log('📄 Error response:', errorData)
      return { error: errorData, status: response.status }
    }
  } catch (error) {
    console.log('❌ Connection error:', error)
    return error
  }
}

export const testFieldCombinations = async () => {
  console.log('🧪 Testing different field name combinations...')
  
  const testCombinations = [
    // Combination 1: Your exact schema (lowercase with underscores)
    {
      name: 'Your Exact Schema',
      data: {
        title: 'Test Event - Exact Schema',
        description: 'Test with your exact field names',
        date: new Date('2024-12-01T10:00:00').toISOString(),
        location: 'Test Location',
        capacity: 10,
        organizer_id: 'test-org-exact'
        // Note: created_at and updated_at are auto-generated by Airtable
      }
    },
    // Combination 2: Minimal required fields only
    {
      name: 'Minimal Fields',
      data: {
        title: 'Test Event - Minimal',
        description: 'Test with minimal fields',
        date: new Date('2024-12-01T10:00:00').toISOString(),
        location: 'Test Location',
        capacity: 10,
        organizer_id: 'test-org-minimal'
      }
    },
    // Combination 3: Alternative naming
    {
      name: 'Alternative Names',
      data: {
        name: 'Test Event - Alt Names',
        desc: 'Test with alternative names',
        event_date: '2024-12-01T10:00:00.000Z',
        venue: 'Test Location',
        max_capacity: 10,
        organizer: 'test-org-alt'
      }
    }
  ]
  
  for (const combination of testCombinations) {
    console.log(`\n🔍 Testing ${combination.name}...`)
    
    try {
      const response = await fetch(`https://api.airtable.com/v0/${import.meta.env.VITE_AIRTABLE_BASE_ID}/Events`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${import.meta.env.VITE_AIRTABLE_API_KEY}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          records: [{ fields: combination.data }]
        })
      })
      
      if (response.ok) {
        const result = await response.json()
        console.log(`✅ ${combination.name} worked!`, result)
        return { success: combination.name, data: result }
      } else {
        const error = await response.text()
        console.log(`❌ ${combination.name} failed:`, error)
      }
    } catch (error) {
      console.log(`❌ ${combination.name} error:`, error)
    }
  }
  
  console.log('🏁 All combinations tested')
}

// Make functions available globally for console testing
if (typeof window !== 'undefined') {
  ;(window as any).airtableDebug = {
    testSchema: testAirtableSchema,
    listEvents: listAirtableEvents,
    debugConnection: debugAirtableConnection,
    testFieldCombinations: testFieldCombinations
  }
  
  console.log('🔧 Airtable debug utilities available at window.airtableDebug')
  console.log('📋 Available methods:')
  console.log('  - debugConnection(): Check connection and see actual fields')
  console.log('  - testFieldCombinations(): Test different field name patterns')
  console.log('  - testSchema(): Test event creation with current schema')
  console.log('  - listEvents(): List existing events')
}